### ISSUE TITLE
Not updated anymore?

### ISSUE THREAD

**Issue by cadilhac** [Hypercubed/angular-commonmark#3]
Just downloaded the latest commonmark.js and your code breaks. DocParser has been replaced by Parser.

**Comment by Hypercubed** [comment]
Thank you for letting me know... I will fix it soon.

**Comment by Hypercubed** [comment]
A fix is in tehe develop branch.

**Comment by mattnathan** [comment]
Any chance this could be released to bower? I just ran into the same issue.

**Comment by Hypercubed** [comment]
Done.
